package com.example.fighterjetsroom.DB

import com.example.fighterjetsroom.model.FighterJet

object fighterJets {

    val fighterJets : List<FighterJet> = listOf(
        FighterJet("MiG-29","https://theaviationgeekclub.com/wp-content/uploads/2022/03/Ukrainian-Air-Force-MiG-29.png","The Mikoyan MiG-29 (Russian: Микоян МиГ-29; NATO reporting name: Fulcrum) is a twin-engine fighter aircraft designed in the Soviet Union. Developed by the Mikoyan design bureau as an air superiority fighter during the 1970s, the MiG-29, along with the larger Sukhoi Su-27, was developed to counter new U.S. fighters such as the McDonnell Douglas F-15 Eagle and the General Dynamics F-16 Fighting Falcon.[2] The MiG-29 entered service with the Soviet Air Forces in 1983.\n" +
                "\n" +
                "While originally oriented towards combat against any enemy aircraft, many MiG-29s have been furnished as multirole fighters capable of performing a number of different operations, and are commonly outfitted to use a range of air-to-surface armaments and precision munitions. The MiG-29 has been manufactured in several major variants, including the multirole Mikoyan MiG-29M and the navalised Mikoyan MiG-29K; the most advanced member of the family to date is the Mikoyan MiG-35. Later models frequently feature improved engines, glass cockpits with HOTAS-compatible flight controls, modern radar and infrared search and track (IRST) sensors, and considerably increased fuel capacity; some aircraft have also been equipped for aerial refueling.\n" +
                "\n" +
                "Following the dissolution of the Soviet Union, the militaries of multiple ex-Soviet republics have continued to operate the MiG-29, the largest of which is the Russian Aerospace Forces. The Russian Aerospace Forces wanted to upgrade its existing fleet to the modernised MiG-29SMT configuration, but financial difficulties have limited deliveries. The MiG-29 has also been a popular export aircraft; more than 30 nations either operate or have operated the aircraft to date. ",8,2500.0,1300.0,0),
        FighterJet("F-35","https://www.insideedition.com/sites/default/files/images/2023-09/f35stealthjet.jpg","The Lockheed Martin F-35 Lightning II is an American family of single-seat, single-engine, all-weather stealth multirole combat aircraft that is intended to perform both air superiority and strike missions. It is also able to provide electronic warfare and intelligence, surveillance, and reconnaissance capabilities. Lockheed Martin is the prime F-35 contractor, with principal partners Northrop Grumman and BAE Systems. The aircraft has three main variants: the conventional takeoff and landing (CTOL) F-35A, the short take-off and vertical-landing (STOVL) F-35B, and the carrier-based (CV/CATOBAR) F-35C.\n" +
                "\n" +
                "The aircraft descends from the Lockheed Martin X-35, which in 2001 beat the Boeing X-32 to win the Joint Strike Fighter (JSF) program. Its development is principally funded by the United States, with additional funding from program partner countries from the North Atlantic Treaty Organization (NATO) and close U.S. allies, including the United Kingdom, Australia, Canada, Italy, Norway, Denmark, the Netherlands, and formerly Turkey.[5][6][7] Several other countries have also ordered, or are considering ordering, the aircraft. The program has drawn much scrutiny and criticism for its unprecedented size, complexity, ballooning costs, and much-delayed deliveries.[8][N 1] The acquisition strategy of concurrent production of the aircraft while it was still in development and testing led to expensive design changes and retrofits.[10][11]\n" +
                "\n" +
                "The F-35 first flew in 2006 and entered service with the U.S. Marine Corps F-35B in July 2015, followed by the U.S. Air Force F-35A in August 2016 and the U.S. Navy F-35C in February 2019.[1][2][3] The aircraft was first used in combat in 2018 by the Israeli Air Force.[12] The U.S. plans to buy 2,456 F-35s through 2044, which will represent the bulk of the crewed tactical aviation of the U.S. Air Force, Navy, and Marine Corps for several decades; the aircraft is planned to be a cornerstone of NATO and U.S.-allied air power and to operate until 2070.",8,2500.0,1300.0,1),
        FighterJet("Su-27","https://upload.wikimedia.org/wikipedia/commons/a/ad/Sukhoi_su-27_%28blue%29_flying_in_sky.jpg","The Sukhoi Su-27 (Russian: Сухой Су-27; NATO reporting name: Flanker) is a Soviet-origin twin-engine supermaneuverable fighter aircraft designed by Sukhoi. It was intended as a direct competitor for the large US fourth-generation jet fighters such as the Grumman F-14 Tomcat and McDonnell Douglas F-15 Eagle, with 3,530-kilometre (1,910 nmi) range, heavy aircraft ordnance, sophisticated avionics and high maneuverability. The Su-27 was designed for air superiority missions, and subsequent variants are able to perform almost all aerial warfare operations. It was designed with the Mikoyan MiG-29 as its complement.\n" +
                "\n" +
                "The Su-27 entered service with the Soviet Air Forces in 1985. The primary role was long range air defence against American SAC Rockwell B-1B Lancer and Boeing B-52G and H Stratofortress bombers, protecting the Soviet coast from aircraft carriers and flying long range fighter escort for Soviet heavy bombers such as the Tupolev Tu-95, Tupolev Tu-22M and Tupolev Tu-160.[2]\n" +
                "\n" +
                "The Su-27 was developed into a family of aircraft these include the Su-30, a two-seat, dual-role fighter for all-weather, air-to-air and air-to-surface deep interdiction missions, and the Su-33, a naval fleet defense interceptor for use from aircraft carriers. Further versions include the side-by-side two-seat Su-34 strike/fighter-bomber variant, and the Su-35 improved air superiority and multi-role fighter. A thrust-vectoring version was created, called the Su-37. The Shenyang J-11 is a Chinese license-built version of the Su-27.",8,2500.0,1300.0,2),
        FighterJet("F-117", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/F-117_Nighthawk_Front.jpg/1200px-F-117_Nighthawk_Front.jpg", "The Lockheed F-117 Nighthawk is a retired American single-seat, subsonic twin-engine stealth attack aircraft developed by Lockheed's secretive Skunk Works division and operated by the United States Air Force (USAF). It was the first operational aircraft to be designed with stealth technology.\n" +
                "\n" +
                "Work on what would become the F-117 was commenced in the 1970s as a means of countering increasingly sophisticated Soviet surface-to-air missiles (SAMs). During 1976, the Defense Advanced Research Projects Agency (DARPA) issued Lockheed with a contract to produce the Have Blue technology demonstrator, the test data from which validated the concept. On 1 November 1978, it was decided to proceed with the F-117 development program. A total of five prototypes would be produced; the first of which performed its maiden flight during 1981 at Groom Lake, Nevada. The first production F-117 was delivered in 1982, and its initial operating capability was achieved in October 1983. All aircraft were initially based at Tonopah Test Range Airport, Nevada.\n" +
                "\n" +
                "The aircraft's faceted shape (made from two-dimensional flat surfaces) heavily contributes to its relatively low radar cross-section of about 0.001 m2 (0.0108 sq ft). To minimise its infrared signature, it has a non-circular tail pipe that mixes hot exhaust with cool ambient air and lacks afterburners; it is also restricted to subsonic speeds as breaking the sound barrier would produce an obvious sonic boom that would increase both its acoustic and infrared footprints. While its performance in air combat maneuvering was less than that of most contemporary fighters, it was strictly an attack aircraft despite being commonly referred to as the \"Stealth Fighter\". For this reason, it is equipped with integrated sophisticated digital navigation and attack systems, targeting being achieved via a thermal imaging infrared system and a laser rangefinder/laser designator. It is aerodynamically unstable in all three aircraft principal axes and thus requires constant flight corrections via a fly-by-wire (FBW) flight system to maintain controlled flight.\n" +
                "\n" +
                "Even years following its entry to service, the F-117 was a black project, its existence being denied by USAF officials. On 10 November 1988, the F-117 was publicly acknowledged for the first time. Its first combat mission was flown during the United States invasion of Panama in 1989. The last of 59 production F-117s were delivered on 3 July 1990. The F-117 was widely publicized for its role in the Gulf War of 1991, having flown approximately 1,300 sorties and scored direct hits on what the US called 1,600 high-value targets in Iraq. F-117s also participated in the conflict in Yugoslavia, during which one was shot down by a surface-to-air missile (SAM) in 1999. It was also active during Operation Enduring Freedom in 2001 and Operation Iraqi Freedom in 2003. The USAF retired the F-117 in April 2008, primarily due to the fielding of the F-22 Raptor.[4] Despite the type's official retirement, a portion of the fleet has been kept in airworthy condition, and F-117s have been observed flying since 2009.", 30, 4000.0, 1000.0, 9),
        FighterJet("F-22","https://media.defense.gov/2021/Sep/17/2002856354/2000/2000/0/210911-Z-DY403-9158.JPG","The Lockheed Martin/Boeing F-22 Raptor is an American single-seat, twin-engine, supersonic all-weather stealth fighter aircraft developed for the United States Air Force (USAF). As a product of the USAF's Advanced Tactical Fighter (ATF) program the aircraft was designed as an air superiority fighter, but also incorporates ground attack, electronic warfare, and signals intelligence capabilities. The prime contractor, Lockheed Martin, built most of the F-22's airframe and weapons systems and conducted final assembly, while program partner Boeing provided the wings, aft fuselage, avionics integration, and training systems.\n" +
                "\n" +
                "The aircraft first flew in 1997 and was variously designated F-22 and F/A-22 before it formally entered service in December 2005 as the F-22A. Although the USAF had originally planned to buy a total of 750 ATFs, the program was cut to 187 production aircraft in 2009 due to high costs, a lack of air-to-air missions at the time of production, and the development of the more affordable and versatile F-35.[N 2] The last F-22 was delivered in 2012.\n" +
                "\n" +
                "While it had a protracted development and initial operational difficulties, the F-22 has become a critical component of the USAF's tactical airpower. The fighter's combination of stealth, aerodynamic performance, and mission systems enabled a leap in air combat capabilities and set the benchmark for its generation.",10,2300.0,2600.0,3),
        FighterJet("Su-57","https://cdn-media.tass.ru/width/1020_b9261fa1/tass/m2/en/uploads/i/20201102/1290143.jpg","The Sukhoi Su-57 (Russian: Сухой Су-57; NATO reporting name: Felon)[5][6] is a twin-engine stealth multirole fighter aircraft developed by Sukhoi.[7] It is the product of the PAK FA (Russian: ПАК ФА, short for: Перспективный авиационный комплекс фронтовой авиации, romanized: Perspektivnyy Aviatsionnyy Kompleks Frontovoy Aviatsii, lit. ''prospective aeronautical complex of front-line air forces'') programme, which was initiated in 1999 as a more modern and affordable alternative to the MFI (Mikoyan Project 1.44/1.42).\n" +
                "\n" +
                "Sukhoi's internal designation for the aircraft is T-50. The Su-57 is the first aircraft in Russian military service designed with stealth technology and is intended to be the basis for a family of stealth combat aircraft.\n" +
                "\n" +
                "A 5th-generation multirole fighter capable of aerial combat as well as ground and maritime strike, the Su-57 incorporates stealth, supermaneuverability, supercruise, integrated avionics, and large internal payload capacity.[8] The aircraft is expected to succeed the MiG-29 and Su-27 in the Russian military service and has also been marketed for export. The first prototype aircraft flew in 2010, but the program experienced a protracted development due to various structural and technical issues that emerged during trials, including the destruction of the first production aircraft in a crash before its delivery.\n" +
                "\n" +
                "After repeated delays, the first Su-57 entered service with the Russian Aerospace Forces (VKS)[N 2] in December 2020.[9] Not counting prototype test aircraft, a total of 11 had been produced as of December 2022",6,2500.0,2700.0,4),
        FighterJet("F/A 18 Super Hornet", "https://seapowermagazine.org/wp-content/uploads/2023/03/230321-N-DU622-1087-scaled.jpg", "The Boeing F/A-18E and F/A-18F Super Hornet are supersonic twin-engine, carrier-capable, multirole fighter aircraft variants derived from the McDonnell Douglas F/A-18 Hornet series. The F/A-18E single-seat and F/A-18F tandem-seat variants are larger and more advanced versions of the F/A-18C and D Hornet.\n" +
                "\n" +
                "The Super Hornet has an internal 20mm M61A2 rotary cannon and can carry air-to-air missiles, air-to-surface and a variety of other weapons. Additional fuel can be carried in up to five external fuel tanks and the aircraft can be configured as an airborne tanker by adding an external air-to-air refueling system.\n" +
                "\n" +
                "Designed and initially produced by McDonnell Douglas, the Super Hornet first flew in 1995. Low-rate production began in early 1997 with full-rate production starting in September 1997, after the merger of McDonnell Douglas and Boeing the previous month. The Super Hornet entered fleet service with the United States Navy in 1999, replacing the Grumman F-14 Tomcat, which was retired in 2006; the Super Hornet has served alongside the original Hornet. The Royal Australian Air Force (RAAF), which has operated the F/A-18A as its main fighter since 1984, ordered the F/A-18F in 2007 to replace its aging General Dynamics F-111C fleet. RAAF Super Hornets entered service in December 2010. In February 2023, Boeing announced plans to end production of the Super Hornet in 2025.", 10, 2400.55, 3000.0, 5),

        FighterJet("Dassault Rafale", "https://upload.wikimedia.org/wikipedia/commons/6/6c/Dassault_Rafale_100letpart225.jpg", "The Dassault Rafale (French pronunciation: [ʁafal], literally meaning \"gust of wind\",[2] or \"burst of fire\" in a more military sense)[3] is a French twin-engine, canard delta wing, multirole fighter aircraft designed and built by Dassault Aviation. Equipped with a wide range of weapons, the Rafale is intended to perform air supremacy, interdiction, aerial reconnaissance, ground support, in-depth strike, anti-ship strike and nuclear deterrence missions. The Rafale is referred to as an \"omnirole\" aircraft by Dassault.\n" +
                "\n" +
                "In the late 1970s, the French Air Force and French Navy were seeking to replace and consolidate their existing fleets of aircraft. In order to reduce development costs and boost prospective sales, France entered into an arrangement with the UK, Germany, Italy and Spain to produce an agile multi-purpose \"Future European Fighter Aircraft\" (which would become the Eurofighter Typhoon). Subsequent disagreements over workshare and differing requirements led to France's pursuit of its own development programme. Dassault built a technology demonstrator which first flew in July 1986 as part of an eight-year flight-test programme, paving the way for the go-ahead of the project. The Rafale is distinct from other European fighters of its era in that it is almost entirely built by one country, involving most of France's major defence contractors, such as Dassault, Thales and Safran.\n" +
                "\n" +
                "Many of the aircraft's avionics and features, such as direct voice input, the RBE2 AA active electronically scanned array (AESA) radar and the optronique secteur frontal infra-red search and track (IRST) sensor, were domestically developed and produced for the Rafale programme. Originally scheduled to enter service in 1996, the Rafale suffered significant delays due to post-Cold War budget cuts and changes in priorities. There are three main variants: Rafale C single-seat land-based version, Rafale B twin-seat land-based version, and Rafale M single-seat carrier-based version.\n" +
                "\n" +
                "Introduced in 2001, the Rafale is being produced for both the French Air Force and for carrier-based operations in the French Navy. The Rafale has been marketed for export to several countries, and was selected for purchase by the Egyptian Air Force, the Indian Air Force, the Qatar Air Force, the Hellenic Air Force, the Croatian Air Force, the Indonesian Air Force and the United Arab Emirates Air Force. The Rafale has been used in combat over Afghanistan, Libya, Mali, Iraq and Syria.", 10, 2100.0, 1900.50, 6),
         FighterJet("Chengdu J-20", "https://twt-thumbs.washtimes.com/media/image/2022/11/09/ring_c0-0-6000-3498_s1770x1032.jpg?9d7096aeca3ec7f2519d7053fff6a8b9ce910225", "The Chengdu J-20 (Chinese: 歼-20; pinyin: Jiān-Èrlíng), also known as Mighty Dragon (Chinese: 威龙; pinyin: Wēilóng,[9][10][11] NATO reporting name: Fagin)[12] is a twinjet all-weather stealth[13] fighter aircraft developed by China's Chengdu Aerospace Corporation for the People's Liberation Army Air Force (PLAAF).[5] The J-20 is designed as an air superiority fighter with precision strike capability.[14] The aircraft has three variants: the initial production model J-20A, the thrust-vectoring J-20B, and twin-seat aircraft teaming capable J-20S.\n" +
                 "\n" +
                 "Descending from the J-XX program of the 1990s,[15] the aircraft made its maiden flight on 11 January 2011,[1][2] and was officially revealed at the 2016 China International Aviation & Aerospace Exhibition.[16] The aircraft entered service in March 2017[5] with the first J-20 combat unit formed in February 2018,[5] making China the second country in the world and the first in Asia to field an operational stealth aircraft.[17] The J-20 is the world's third operational fifth-generation fighter aircraft after the American F-22 and F-35.[17]", 8, 3000.0, 2000.0, 7),
        FighterJet("Su-35", "https://img.ednews.net/news/2020/04/photo_423439.jpg", "The Sukhoi Su-35 (Russian: Сухой Су-35; NATO reporting name: Flanker-E) is the designation for two improved derivatives of the Su-27 air-defence fighter. They are single-seat, twin-engine, supermaneuverable air superiority fighters, designed by the Sukhoi Design Bureau and built by Sukhoi.\n" +
                "\n" +
                "The type was originally developed by the Soviet Union from the Su-27 and was known as the Su-27M. It incorporated canards and a multi-function radar giving it multi-role capabilities. The first prototype made its maiden flight in June 1988. Following the dissolution of the Soviet Union Sukhoi re-designated it as the Su-35 to attract export orders. Fourteen aircraft were produced and used for tests and demonstrations; one example had thrust-vectoring engines and was in turn redesignated the Su-37. A sole Su-35UB two-seat trainer was also built in the late 1990s that resembled the Su-30MK family.\n" +
                "\n" +
                "In 2003, Sukhoi embarked on a second modernization of the Su-27 to serve as an interim aircraft awaiting the development of the Sukhoi PAK FA (Su-57) program. Also known as the Su-35, this version has a redesigned cockpit and weapons-control system and features thrust-vectoring engines in place of the canards. The type made its first flight in February 2008. Although it was designed for export, the Russian Air Force became the launch customer in 2009, with the production version designated Su-35S. China's People's Liberation Army Air Force has also placed orders.", 10, 21050.0, 2500.0, 8),
        FighterJet("Tu-22M3", "https://www.forces.net/sites/default/files/Image%20ID%202BERWH4%20Russian%20Air%20Force%20Tu-22%20taking%20off%20at%20Dyagilevo%20Air%20Base%2C%20Russia%206818%20CREDIT%20ALAMY.png", "The Tupolev Tu-22M (Russian: Туполев Ту-22М; NATO reporting name: Backfire) is a supersonic, variable-sweep wing, long-range strategic and maritime strike bomber developed by the Tupolev Design Bureau in the 1960s. The bomber was reported as being designated Tu-26 by western intelligence at one time.[1] During the Cold War, the Tu-22M was operated by the Soviet Air Forces (VVS) in a missile carrier strategic bombing role, and by the Soviet Naval Aviation (Aviatsiya Voyenno-Morskogo Flota, AVMF) in a long-range maritime anti-shipping role.[2] As of 2021, there were 66 of the aircraft in service", 40, 3000.0, 1500.0, 10),

        FighterJet("F-16", "https://www.globaldefence.info/wp-content/uploads/2019/01/F-16V_CFTs-in-hangar_1920.jpg.pc-adaptive.full_.medium.jpeg", "The General Dynamics F-16 Fighting Falcon is an American single-engine supersonic multirole fighter aircraft originally developed by General Dynamics for the United States Air Force (USAF). Designed as an air superiority day fighter, it evolved into a successful all-weather multirole aircraft. Over 4,600 aircraft have been built since production was approved in 1976.[4] Although no longer being purchased by the U.S. Air Force, improved versions are being built for export customers. In 1993, General Dynamics sold its aircraft manufacturing business to the Lockheed Corporation,[5] which in turn became part of Lockheed Martin after a 1995 merger with Martin Marietta.[6]\n" +
                "\n" +
                "The Fighting Falcon's key features include a frameless bubble canopy for good visibility, side-mounted control stick to ease control while maneuvering, an ejection seat reclined 30 degrees from vertical to reduce the effect of g-forces on the pilot, and the first use of a relaxed static stability/fly-by-wire flight control system that helps to make it an agile aircraft. The F-16 has an internal M61 Vulcan cannon and 11 hardpoints.\n" +
                "\n" +
                "In addition to active duty in the U.S. Air Force, Air Force Reserve Command, and Air National Guard units, the aircraft is also used by the U.S. Air Force Thunderbirds aerial demonstration team, the US Air Combat Command F-16 Viper Demonstration Team,[7] and as an adversary/aggressor aircraft by the United States Navy. The F-16 has also been procured to serve in the air forces of 25 other nations.[8] As of 2015, it was the world's most numerous fixed-wing aircraft in military service.", 9, 1500.0,1900.0,11)

    )

    fun getAllJets(): List<FighterJet> {
        return fighterJets
    }

    fun getAllJetIds(): List<Int> {
        return fighterJets.map { it.id }
    }




}